# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "sandbox.example.com"
  # config.vm.network "private_network", ip: "10.10.10.10"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.ssh.forward_agent = true
  
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  Vagrant.configure("2") do |config|
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

end
