# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  # config.vm.box = "opscode_centos-6.5"
  # config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"
  
  # config.vm.box = "opscode_debian-7.4"
  # config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box"
  
  # config.vm.box = "opscode_ubuntu-14.04"
  # config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"
  
  config.vm.hostname = "sandbox.example.com"
  
  config.vm.network "private_network", ip: "10.10.10.10"
  
  config.vm.provider "virtualbox" do |vb|
  # vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  # config.ssh.forward_agent = true
  
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  # Vagrant.configure("2") do |config|
  #   config.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "playbook.yml"
  #   end
  # end

  # Vagrant.configure("2") do |config|
  #   config.omnibus.chef_version = :latest
  # end

  # Vagrant.configure("2") do |config|
  #   config.vm.provision "chef_solo" do |chef|
  #     chef.cookbooks_path = "my_cookbooks"
  #     chef.add_recipe "apache"
  #     chef.roles_path = "my_roles
  #     chef.add_role("web")
  #   end
  # end

end
