set shell=bash
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/

call vundle#begin()
Plugin 'Lokaltog/vim-easymotion'
Plugin 'Shougo/neocomplcache.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-airline'
Plugin 'chase/vim-ansible-yaml'
Plugin 'fatih/vim-go'
Plugin 'gmarik/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'rking/ag.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'sjl/gundo.vim'
Plugin 'tmhedberg/SimpylFold'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-perl/vim-perl'
Plugin 'vim-ruby/vim-ruby'
call vundle#end() 

" Syntasic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Make neocomplcache play nicer
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
let g:neocomplcache_enable_at_startup = 1

" Make Python syntax completion awesome
let python_highlight_all = 1

" What would I do witout nerdtree?
map <C-n> :NERDTreeToggle <CR>

" Toggle comments
map <Leader>c gc

" The magical undo
nnoremap <leader>u :GundoToggle<CR>

" Make vim-airline always show up
set laststatus=2

" Syntax and File Types
filetype plugin indent on
syntax enable

" The fine appeal
set t_Co=256
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

" Tabs are evil
set expandtab
set tabstop=4 shiftwidth=4 softtabstop=4
set autoindent
set wildmenu

" Search Optimizations
set incsearch
set hlsearch
set cursorline
set cursorcolumn
hi CursorLine cterm=bold ctermbg=0

" Enable folding
nnoremap <space> za
let g:SimpylFold_docstring_preview=1
let g:SimpylFold_fold_docstring=0
let g:SimpylFold_fold_import=0

" Line numbering
set relativenumber 
set number

function! NumberToggle()
  setl rnu!
  setl nu!
endfunc

nnoremap <Leader>n :call NumberToggle() <CR>

" No more committing swp files to git
set backupdir=/tmp
set directory=/tmp

" Save and run
map <leader>r :w<CR>: !clear && ./%<CR>
