set shell=bash
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/

call plug#begin('~/.vim/plugged')
Plug 'Lokaltog/vim-easymotion'
Plug 'Shougo/neocomplcache.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'bling/vim-airline'
Plug 'chase/vim-ansible-yaml'
Plug 'fatih/vim-go'
Plug 'gmarik/Vundle.vim'
Plug 'kien/ctrlp.vim'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'sjl/gundo.vim'
Plug 'tmhedberg/SimpylFold'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'vim-perl/vim-perl'
Plug 'vim-ruby/vim-ruby'
call plug#end()

" Syntasic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Make neocomplcache play nicer
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
let g:neocomplcache_enable_at_startup = 1

" Make Python syntax completion awesome
let python_highlight_all = 1

" What would I do witout nerdtree?
map <C-n> :NERDTreeToggle <CR>

" Toggle comments
map <Leader>c gc

" The magical undo
nnoremap <leader>u :GundoToggle<CR>

" Make vim-airline always show up
set laststatus=2

" Syntax and File Types
filetype plugin indent on
syntax enable

" The fine appeal
set t_Co=256
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

" Tabs are evil
set expandtab
set tabstop=4 shiftwidth=4 softtabstop=4
set autoindent
set wildmenu

" Search Optimizations
set incsearch
set hlsearch
set cursorline
set cursorcolumn
hi CursorLine cterm=bold ctermbg=0

" Enable folding
nnoremap <space> za
let g:SimpylFold_docstring_preview=1
let g:SimpylFold_fold_docstring=0
let g:SimpylFold_fold_import=0

" Line numbering
set relativenumber 
set number

function! NumberToggle()
  setl rnu!
  setl nu!
endfunc

nnoremap <Leader>n :call NumberToggle() <CR>

" No more committing swp files to git
set backupdir=/tmp
set directory=/tmp

" Save and run
map <leader>r :w<CR>: !clear && ./%<CR>

" Save ,quit, or not
map <leader>w :wa<CR>
map <leader>x :xa<CR>
map <leader>q :qa!<CR>
