---
- name: Install all packages
  include: packages.yml
  tags:
    - packages

- name: Manage all services
  include: services.yml
  tags:
    - services

- name: Manage all users
  include: users.yml
  tags:
    - users

- name: Configure git
  include: git.yml
  tags:
    - git
  become: yes
  become_user: navid
  become_method: sudo

- name: Configure bash
  include: bash.yml
  tags:
    - bash
  become: yes
  become_user: navid
  become_method: sudo

- name: Configure vim
  include: vim.yml
  tags:
    - vim

- name: Configure ssh
  include: ssh.yml
  tags:
    - ssh
  become: yes
  become_user: navid
  become_method: sudo

- name: Install aur packages
  include: aur.yml
  tags:
    - aur
  become: yes
  become_user: navid
  become_method: sudo

- name: Install kernel modules for Virtualbox
  include: virtualbox.yml
  tags:
    - virtualbox
