---
# - name: Install all packages
#   include_tasks: packages.yml
#   args:
#     apply:
#       become: yes
#       become_method: sudo
 
- name: Configure git
  include_tasks: git.yml

- name: Configure zsh
  include_tasks: zsh.yml

- name: Configure vim
  include_tasks: vim.yml

- name: Configure ssh
  include_tasks: ssh.yml
