---
- name: Uninstall vi because it sucks
  pacman: name={{ item }} state=absent
  with_items:
    - vi

- name: All the packages in one go
  pacman: name={{ item }} state=present
  with_items:
    - bash-completion
    - chromium
    - dmenu
    - docker
    - docker-compose
    - dosfstools
    - feh
    - git
    - gvim
    - htop
    - i3
    - iftop
    - iotop
    - libreoffice-still
    - mtools
    - mtr
    - net-tools # For Virtualbox networking
    - networkmanager
    - nmap
    - ntfs-3g
    - openssh
    - openvpn
    - parcellite
    - pcmanfm
    - ponymix
    - pulseaudio
    - rsync
    - rxvt-unicode
    - scrot
    - sddm
    - sshpass
    - the_silver_searcher
    - transmission-cli
    - ttf-dejavu
    - ttf-liberation
    - vagrant
    - virtualbox
    - virtualbox-host-dkms
    - vlc
    - whois
    - xf86-input-synaptics
    - xf86-video-intel
    - xorg-server
    - xorg-xbacklight
    - zathura
    - zathura-pdf-poppler
