---
- name: Symlink few configuration files from the repo
  file: src={{ dotfiles }}/{{ item.src }}
        dest=~/{{ item.dest }}
        state=link
        force=yes
  with_items:
    - { src: 'vimrc', dest: '.vimrc' }

- name: Create ~/.vim/autoload
  file: path=~/.vim/autoload
        state=directory

- name: Install vim-plug
  get_url: url='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
           dest=~/.vim/autoload/plug.vim
