---
- name: Load the Virtualbox kernel modules
  modprobe: name={{ item }}
  with_items:
    - vboxdrv
    - vboxnetadp
    - vboxnetflt

- name: Load the Virtualbox kernel modules at boot
  copy: src=virtualbox.conf
        dest=/etc/modprobe.d/virtualbox.conf
